### ISSUE TITLE
addPVAGradCost2CT中phidotcost和latacccost为什么不计算了

### ISSUE THREAD

**Issue by renjingc** [ZJU-FAST-Lab/Dftpav#10]
![2023-09-05_16-39](https://github.com/ZJU-FAST-Lab/Dftpav/assets/9279431/a050c6a9-af88-4385-8a9a-a5f01432e2f4)
![2023-09-05_16-39_1](https://github.com/ZJU-FAST-Lab/Dftpav/assets/9279431/a5498bb1-7bd4-492c-a68a-2ad36e1dde26)

我看traj_optimizer.cc中addPVAGradCost2CT phidotcost和latacccost都不计算了，那横向加速度和kappa的cost是在哪计算的？

**Comment by Han-Sin** [comment]
kappa就是曲率，这个计算了的，phidot是曲率的变化率。
latacccost可以取消注释，就计算了
