### ISSUE TITLE
Rviz shut down when planning is triggered

### ISSUE THREAD

**Issue by DyedBamboo** [ZJU-FAST-Lab/Dftpav#3]
When I use 2D Nav Goal in RVIZ to trigger the planning, RVIZ exits and throws the following error:
![image](https://user-images.githubusercontent.com/62492797/232270429-ac7491ef-ce2f-442d-8b73-fe0c291a36fe.png)
I'm using ROS noetic
The eigen version is 3.3.7

**Comment by DyedBamboo** [comment]
The error occurs when I compile in Debug mode.

**Comment by chennnuo** [comment]
@DyedBamboo I also encountered the same problem, did you finally solve it?

**Comment by yinuo-song** [comment]
May I know how did you solve this problem then?

**Comment by Luoyuhao12345** [comment]
> May I know how did you solve this problem then?

I solved this problem by using catkin_make -DCMAKE_BUILD_TYPE=Release instead of catkin_make

**Comment by hjw08** [comment]
@Luoyuhao12345 我这样编译后还是会报REQUIRED process [rviz-2] has died，只不过程序不会直接die了，然后一直显示no map update，请问您有遇到这种情况吗？
