### ISSUE TITLE
trajectory kappa is not in kappa constraint 

### ISSUE THREAD

**Issue by Hasakiya** [ZJU-FAST-Lab/Dftpav#5]
Hello, in the process of using the code, I found that the curvature of the planned trajectory would not conform to the curvature constraint. May I ask whether the constraint became a soft constraint after being converted into the objective function?
![image](https://github.com/ZJU-FAST-Lab/Dftpav/assets/51686482/0b4e8e9c-3ca8-4de6-9612-f854f8e3d52e)（forward and backward max kappa is  1）

**Comment by Han-Sin** [comment]
From a theoretical perspective, soft constraints should also be limited within an acceptable range. However, in this case, the violation is clearly excessive and unscientific.
After debugging, we discovered a parameter bug in this version of the code. The penalty weight for the curvature feasibility constraint was noticeably small, so we increased it accordingly. Additionally, the completeness and quality of our algorithm depend on the number of polynomial pieces, which we also slightly increased.
After resolving these bugs, the maximum curvature was 1.01, and the amount of violation was within an acceptable range. Thank you for bringing this issue to our attention, and we have updated the code accordingly.

If you require  more detailed technical assistance, please feel free to contact me: zhichaohan@zju.edu.cn
