### ISSUE TITLE
Question about the safe corridor building 

### ISSUE THREAD

**Issue by DyedBamboo** [ZJU-FAST-Lab/Dftpav#6]
代码中构造安全走廊是在这里调用的吗？https://github.com/ZJU-FAST-Lab/Dftpav/blob/1808107b7fb6fe459f38154e355010a854e4575f/src/Plan/traj_planner/src/traj_manager.cpp#LL573C14-L573C14

为什么不是调用这个函数呢？https://github.com/ZJU-FAST-Lab/Dftpav/blob/1808107b7fb6fe459f38154e355010a854e4575f/src/Plan/traj_planner/src/traj_manager.cpp#LL918C3-L920C73

**Comment by Han-Sin** [comment]
是的，其实两种方法都行，开源里用了一种比较简单的走廊构造方式来方便初学者理解

**Comment by xzh-20** [comment]
您好，我有一个不太理解的地方，这求解带状矩阵Mc=b时，
 inline void generate(const Eigen::MatrixXd &inPs,
                            const double &dT,
                            const Eigen::MatrixXd &headState,
                            const Eigen::MatrixXd &tailState)
        {
            headPVA = headState;
            tailPVA = tailState;

            t(1) = dT;
            t(2) = t(1) * t(1);
            t(3) = t(2) * t(1);
            t(4) = t(2) * t(2);
            t(5) = t(4) * t(1);
            tInv = t.cwiseInverse();
            //为什么还要*t(1),t(2)
            b.setZero();
            b.row(0) = headPVA.col(0).transpose();
            b.row(1) = headPVA.col(1).transpose() * t(1);
            b.row(2) = headPVA.col(2).transpose() * t(2);
            for (int i = 0; i < N - 1; i++) {
                b.row(6 * i + 5) = inPs.col(i).transpose();
            }对b进行赋值时，为什么b.row(1) ，b.row(2) 要乘以t（1）和t(2)呢，tailPVA.col(1).transpose()这个我理解是速度把，不太明白为什么乘t(1)，还望解答以下，谢谢
