### ISSUE TITLE
使用2d_navgoal后卡死报错

### ISSUE THREAD

**Issue by qycqycqyc** [ZJU-FAST-Lab/Dftpav#8]
![2023-06-27 10-25-07屏幕截图](https://github.com/ZJU-FAST-Lab/Dftpav/assets/48520573/6b5845a8-9d50-4a76-bd35-3bc0dea12de0)
一开始正常运行，一点击goal后rviz里的车都静止不动了

**Comment by yinuo-song** [comment]
May I know how did you solve this problem so?

**Comment by qycqycqyc** [comment]
> May I know how did you solve this problem so?

把ros的ompl库删了,安装和ros无关的ompl库

**Comment by yinuo-song** [comment]
非常感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月1日(周五) 中午12:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZJU-FAST-Lab/Dftpav] 使用2d_navgoal后卡死报错 (Issue #8)




  
May I know how did you solve this problem so?
  
把ros的ompl库删了,安装和ros无关的ompl库

**Comment by MeYuChen** [comment]
> > May I know how did you solve this problem so?
> 
> 把ros的ompl库删了,安装和ros无关的ompl库

有具体的版本吗 我安装了最新的版本ompl 1.6都会报错

**Comment by qycqycqyc** [comment]
哎？我记得是直接通过apt install 安装的，不带ros的，他的错误就是用到这个库的dubins曲线，这个库有ros版本和非ros版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月4日(周一) 下午3:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ZJU-FAST-Lab/Dftpav] 使用2d_navgoal后卡死报错 (Issue #8)




   
May I know how did you solve this problem so?
  
把ros的ompl库删了,安装和ros无关的ompl库
  
有具体的版本吗 我安装了最新的版本ompl 1.6都会报错

**Comment by qycqycqyc** [comment]
sudo apt-get install libompl* 即可

**Comment by MeYuChen** [comment]
> sudo apt-get install libompl* 即可

非常感谢您的答复，确实这样可以成功，除了卸载ros版本的ompl以外，官方的源码安装的也需要卸载才可以。

**Comment by yinuo-song** [comment]
嗯嗯～我已经解决了这个问题，非常感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月4日(周一) 下午3:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZJU-FAST-Lab/Dftpav] 使用2d_navgoal后卡死报错 (Issue #8)




  
sudo apt-get install libompl* 即可
  
非常感谢您的答复，确实这样可以成功，除了卸载ros版本的ompl以外，官方的源码安装的也需要卸载才可以。

**Comment by yinuo-song** [comment]
好嘞⊙▽⊙我已经解决了这个问题，非常感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月4日(周一) 下午2:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZJU-FAST-Lab/Dftpav] 使用2d_navgoal后卡死报错 (Issue #8)




 
sudo apt-get install libompl* 即可
